# Generated by Django 4.1.3 on 2024-10-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_usernotificationsmodel_recommendation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotificationsmodel',
            name='recommendation',
            field=models.JSONField(verbose_name='Рекомендации по выращиванию агрокультур'),
        ),
    ]
