# Generated by Django 4.1.3 on 2024-10-10 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_usernotificationsmodel_recommendation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usernotificationsmodel',
            old_name='recommendation',
            new_name='recommendations',
        ),
        migrations.AlterField(
            model_name='usernotificationsmodel',
            name='notification_type',
            field=models.CharField(choices=[('COMMENT_CREATED', 'Комментарий создан'), ('METRICS_UPDATED', 'Метрика обновлена'), ('CROPS_RECOMMENDATIONS_RECEIVED', 'Получен список рекомендаций по выращиванию агрокультур')], max_length=128, null=True, verbose_name='Тип уведомления'),
        ),
    ]
