# Generated by Django 4.1.3 on 2024-10-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_rename_recommendation_usernotificationsmodel_recommendations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotificationsmodel',
            name='recommendations',
        ),
        migrations.AddField(
            model_name='usernotificationsmodel',
            name='recommendation',
            field=models.JSONField(null=True, verbose_name='Рекомендация по выращиванию агрокультуры'),
        ),
    ]
