# Generated by Django 4.1.3 on 2024-10-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastUpdateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('station_code', models.CharField(max_length=10, verbose_name='Код станции')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('forecast', models.JSONField(verbose_name='Прогноз погоды')),
            ],
            options={
                'verbose_name': 'Обновление прогноза погоды',
                'verbose_name_plural': 'Обновления прогнозов погоды',
                'ordering': ['-created'],
            },
        ),
    ]
